name: needs output test

on:
  workflow_call:
jobs:
  test_A:
    name: test A
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.test_1.outputs.result }}
    steps:
      - name: test 1
        id: test_1
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            return 'Successful';

  test_B:
    name: test B
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.test_1.outputs.result }}
    steps:
      - name: test 1
        id: test_1
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            return 'Failed';

  test_result:
    name: test result
    needs: [test_A, test_B]
    if: ${{ always() }}
    uses: ./.github/workflows/reuse_needs_output_test_2.yml
    secrets: inherit
    with:
      needs: ${{ toJSON(needs) }}
